const char* masterStyleSheet = 
"@import url('https://dev-cats.github.io/code-snippets/JetBrainsMono.css');\n"
"* {\n"
"	font-family: 'Jetbrains Mono';\n"
"}\n"
"\n"
":root {\n"
"	--hue: 267;\n"
"	--function: 190;\n"
"\n"
"	--txt-sat: 80%;\n"
"	--txt-lit: 60%;\n"
"}\n"
"\n"
"body {\n"
"	background: hsl(var(--hue), 10%, 10%);\n"
"}\n"
"\n"
".function {\n"
"	width: 20vw;\n"
"	position: relative;\n"
"	margin-right: 2vh;\n"
"	float: left;\n"
"}\n"
".function-name {\n"
"	width: 100%;\n"
"	height: 2vh;\n"
"	position: absolute;\n"
"	background: hsl(var(--hue), 10%, 30%);\n"
"	border: 2px solid black;\n"
"	border-radius: 12px;\n"
"	text-align: center;\n"
"	line-height: 2vh;\n"
"	color: hsl(var(--function), var(--txt-sat), var(--txt-lit));\n"
"}\n"
"\n"
".call {\n"
"	height: 2vh;\n"
"	position: absolute;\n"
"	background: hsl(var(--hue), 10%, 40%);\n"
"	border: 2px solid black;\n"
"	border-radius: 12px;\n"
"	text-align: left;\n"
"	line-height: 2vh;\n"
"	color: hsl(var(--function), var(--txt-sat), var(--txt-lit));\n"
"}\n"
"\n"
;